apiVersion: v1
data:
  oauth2-proxy.cfg: |-
    # Provider config
    provider="github"
    # Client config
    client_id="Ov23livYEKbmBMfWwH1i"
    client_secret="e13393663cb4e79b77d157b670c256d12dab7133"
    cookie_secret="ZzBkN000Wm0pQkVkKUhzMk5YPntQRUw_ME1oMTZZTy0="
    # Upstream config
    http_address="0.0.0.0:4180"
    upstreams="http://10.101.95.46:80"
    email_domains=["*"]
    # Redis session store config
    session_store_type="redis"
    redis_connection_url="redis://redis-service:6379"
kind: ConfigMap
metadata:
  name: oauth2-proxy-config
  namespace: oauth2-proxy
